apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: direct
  orgId: 1
  url: http://localhost:9090
  isDefault: true
  httpMethod: GET
  manageAlerts: true
  version: 1
  editable: false